"""
Visualize Teacher Generated Data

This script loads and visualizes synthetic videos generated by the teacher model,
showing both the RGB frames and the latent trajectory.

Usage:
    python data_proc/visualize_teacher_data.py \
        --data_path data/teacher_synthetic/basketball_001/generation_data.pt \
        --output_dir visualizations/basketball_001
"""

import argparse
import os
import torch
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


def tensor_to_image(tensor):
    """Convert tensor (C, H, W) in [-1, 1] to PIL Image."""
    # Denormalize from [-1, 1] to [0, 1]
    tensor = (tensor + 1.0) / 2.0
    tensor = torch.clamp(tensor, 0, 1)
    
    # Convert to numpy (H, W, C)
    image = tensor.permute(1, 2, 0).cpu().numpy()
    
    # Convert to uint8
    image = (image * 255).astype(np.uint8)
    
    return Image.fromarray(image)


def visualize_video_frames(video_tensor, output_dir, prefix="frame"):
    """Save video frames as images with a grid visualization."""
    os.makedirs(output_dir, exist_ok=True)
    
    # video_tensor shape: (B, C, T, H, W) or (C, T, H, W)
    if video_tensor.ndim == 5:
        video_tensor = video_tensor.squeeze(0)  # Remove batch dim
    
    # (C, T, H, W)
    C, T, H, W = video_tensor.shape
    
    print(f"Video shape: {T} frames of {H}x{W}, {C} channels")
    
    # Save individual frames
    frames_dir = os.path.join(output_dir, "frames")
    os.makedirs(frames_dir, exist_ok=True)
    
    for t in range(T):
        frame = video_tensor[:, t, :, :]  # (C, H, W)
        img = tensor_to_image(frame)
        img.save(os.path.join(frames_dir, f"{prefix}_{t:04d}.png"))
    
    print(f"Saved {T} frames to {frames_dir}")
    
    # Create a grid visualization
    grid_cols = min(6, T)
    grid_rows = (T + grid_cols - 1) // grid_cols
    
    fig, axes = plt.subplots(grid_rows, grid_cols, figsize=(grid_cols * 3, grid_rows * 3))
    if grid_rows == 1 and grid_cols == 1:
        axes = [[axes]]
    elif grid_rows == 1 or grid_cols == 1:
        axes = axes.reshape(grid_rows, grid_cols)
    
    for idx in range(grid_rows * grid_cols):
        row = idx // grid_cols
        col = idx % grid_cols
        
        if idx < T:
            frame = video_tensor[:, idx, :, :]
            img = tensor_to_image(frame)
            axes[row, col].imshow(img)
            axes[row, col].set_title(f"Frame {idx}")
            axes[row, col].axis('off')
        else:
            axes[row, col].axis('off')
    
    plt.tight_layout()
    grid_path = os.path.join(output_dir, "video_grid.png")
    plt.savefig(grid_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"Saved grid visualization to {grid_path}")


def visualize_latent_trajectory(trajectory, output_dir):
    """Visualize the latent trajectory during diffusion."""
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"\nLatent trajectory: {len(trajectory)} saved steps")
    
    # Extract statistics from each step
    steps = []
    timesteps = []
    mean_values = []
    std_values = []
    
    for step_data in trajectory:
        step = step_data['step']
        timestep = step_data['timestep']
        latents = step_data['latents']
        
        steps.append(step)
        timesteps.append(timestep)
        mean_values.append(latents.mean().item())
        std_values.append(latents.std().item())
    
    # Plot trajectory statistics
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    
    # Mean values
    ax1.plot(steps, mean_values, marker='o')
    ax1.set_xlabel('Denoising Step')
    ax1.set_ylabel('Mean Latent Value')
    ax1.set_title('Latent Mean During Denoising')
    ax1.grid(True)
    
    # Std values
    ax2.plot(steps, std_values, marker='o', color='orange')
    ax2.set_xlabel('Denoising Step')
    ax2.set_ylabel('Latent Std Dev')
    ax2.set_title('Latent Std Dev During Denoising')
    ax2.grid(True)
    
    plt.tight_layout()
    trajectory_path = os.path.join(output_dir, "latent_trajectory.png")
    plt.savefig(trajectory_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"Saved trajectory visualization to {trajectory_path}")
    
    # Print trajectory details
    print("\nTrajectory Details:")
    print(f"{'Step':<8} {'Timestep':<12} {'Mean':<12} {'Std':<12}")
    print("-" * 48)
    for i in range(len(steps)):
        print(f"{steps[i]:<8} {timesteps[i]:<12.2f} {mean_values[i]:<12.6f} {std_values[i]:<12.6f}")


def visualize_text_embeddings(text_emb, text, output_dir):
    """Visualize text embedding statistics."""
    os.makedirs(output_dir, exist_ok=True)
    
    # text_emb shape: (B, seq_len, dim)
    text_emb = text_emb.squeeze(0)  # (seq_len, dim)
    seq_len, dim = text_emb.shape
    
    print(f"\nText embedding shape: {seq_len} tokens x {dim} dimensions")
    print(f"Text: \"{text}\"")
    
    # Compute per-token norms
    token_norms = torch.norm(text_emb, dim=1).cpu().numpy()
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    
    # Token norms
    ax1.plot(token_norms, marker='o', markersize=2)
    ax1.set_xlabel('Token Position')
    ax1.set_ylabel('Embedding Norm')
    ax1.set_title('Text Token Embedding Norms')
    ax1.grid(True)
    
    # Embedding heatmap (sample)
    sample_tokens = min(50, seq_len)
    sample_dims = min(100, dim)
    emb_sample = text_emb[:sample_tokens, :sample_dims].cpu().numpy()
    
    im = ax2.imshow(emb_sample.T, aspect='auto', cmap='viridis')
    ax2.set_xlabel('Token Position')
    ax2.set_ylabel('Embedding Dimension (sampled)')
    ax2.set_title(f'Text Embedding Heatmap (first {sample_tokens} tokens)')
    plt.colorbar(im, ax=ax2)
    
    plt.tight_layout()
    text_emb_path = os.path.join(output_dir, "text_embeddings.png")
    plt.savefig(text_emb_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"Saved text embedding visualization to {text_emb_path}")


def main():
    parser = argparse.ArgumentParser(description="Visualize teacher generated data")
    parser.add_argument("--data_path", type=str, required=True,
                        help="Path to generation_data.pt file")
    parser.add_argument("--output_dir", type=str, required=True,
                        help="Directory to save visualizations")
    parser.add_argument("--show_latents", action="store_true",
                        help="Visualize latent trajectory")
    parser.add_argument("--show_text", action="store_true",
                        help="Visualize text embeddings")
    
    args = parser.parse_args()
    
    # Load data
    print(f"Loading data from {args.data_path}")
    data = torch.load(args.data_path, map_location='cpu')
    
    print("\n" + "="*60)
    print("TEACHER GENERATED DATA")
    print("="*60)
    
    # Extract components
    text = data.get('text', 'No text prompt found')
    generated_video = data['generated_video']
    final_latents = data['final_latents']
    latents_trajectory = data.get('latents_trajectory', [])
    text_emb = data.get('text_emb', None)
    
    print(f"\nPrompt: \"{text}\"")
    print(f"Generated video shape: {generated_video.shape}")
    print(f"Final latents shape: {final_latents.shape}")
    print(f"Trajectory steps saved: {len(latents_trajectory)}")
    
    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Visualize video frames
    print("\n" + "-"*60)
    print("Visualizing Video Frames")
    print("-"*60)
    visualize_video_frames(generated_video, args.output_dir)
    
    # Visualize latent trajectory
    if args.show_latents and len(latents_trajectory) > 0:
        print("\n" + "-"*60)
        print("Visualizing Latent Trajectory")
        print("-"*60)
        visualize_latent_trajectory(latents_trajectory, args.output_dir)
    
    # Visualize text embeddings
    if args.show_text and text_emb is not None:
        print("\n" + "-"*60)
        print("Visualizing Text Embeddings")
        print("-"*60)
        visualize_text_embeddings(text_emb, text, args.output_dir)
    
    print("\n" + "="*60)
    print(f"All visualizations saved to {args.output_dir}")
    print("="*60)


if __name__ == "__main__":
    main()

